version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - qdrant
    networks:
      - internal_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - internal_network

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge